# /monitoring/prometheus.yml
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node_backend'
    static_configs:
      - targets: ['node-backend:4000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'ssh_logs'
    static_configs:
      - targets: ['loki:3100']
